# Generated by Django 5.2.7 on 2025-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('company_name', models.CharField(blank=True, max_length=250, null=True)),
                ('location', models.CharField(blank=True, max_length=250, null=True)),
                ('job_type', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20, null=True)),
                ('salary_range', models.CharField(blank=True, max_length=250, null=True)),
                ('job_description', models.TextField(default='Description')),
                ('responsibilities', models.TextField(default='Responsibilities')),
                ('Application_deadline', models.DateField()),
            ],
        ),
    ]
