# Generated by Django 5.2.7 on 2025-10-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='location',
            field=models.CharField(blank=True, choices=[('chennai', 'Chennai'), ('bangalore', 'Bangalore'), ('mumbai', 'Mumbai')], max_length=250, null=True),
        ),
    ]
