# Generated by Django 5.2.7 on 2025-10-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanage', '0002_alter_jobdetails_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
