# Generated by Django 5.2.7 on 2025-10-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanage', '0003_alter_jobdetails_job_type_alter_jobdetails_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdetails',
            name='responsibilities',
        ),
    ]
