# Generated by Django 5.2.7 on 2025-10-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanage', '0004_remove_jobdetails_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='Application_deadline',
            field=models.DateField(blank=True),
        ),
    ]
