# Generated by Django 5.2.7 on 2025-10-22 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanage', '0005_alter_jobdetails_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='Application_deadline',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
    ]
