# Generated by Django 5.2.7 on 2025-10-22 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanage', '0006_alter_jobdetails_application_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='Application_deadline',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(choices=[('', 'Choose Job Type'), ('full_time', 'FullTime'), ('part_time', 'PartTime'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='location',
            field=models.CharField(blank=True, choices=[('', 'Choose Preferred Location'), ('Chennai', 'Chennai'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Mumbai', 'Mumbai'), ('Remote', 'Remote')], max_length=250, null=True),
        ),
    ]
