# Generated by Django 5.2.7 on 2025-10-23 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobmanage', '0007_alter_jobdetails_application_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(choices=[('', 'Choose Job Type'), ('full time', 'FullTime'), ('part time', 'PartTime'), ('contract', 'Contract'), ('internship', 'Internship')], max_length=20, null=True),
        ),
    ]
